debug: true
config: ./configs/
data : ./data/
help: https://github.com/tpc3/Bocchi-Re/wiki
discord:
  token: YOUR_TOKEN_HERE
  status: Bocchi-Re is runnning! | b.help
openai:
  token: YOUR_TOKEN_HERE
guild:
  prefix: b.
  lang: japanese
  model:
    chat: gpt-3.5-turbo
    image: dall-e-2
  reply: 3
  maxtokens: 1000
  defaultTemperature: 0.2
user_blacklist:
- "0000000000000000000"