package config

type Strings struct {
	Lang    string
	Error   errorstr
	Warning warning
	Reply   reply
	Content content
}

type errorstr struct {
	Title                string
	Unkown               string
	SubCmd               string
	NoModel              string
	NoImg                string
	TooLongResponse      string
	BrokenLink           string
	NoSupportedFormat    string
	RejectedSafetySystem string
	NoSupportedSize      string
	CantGetImage         string
	Invalid              string
	NoVisionModel        string
}

type warning struct {
	Title                     string
	NoSupportedParameterText  string
	NoSupportedParameterImage string
	DataSaveError             string
	NoResponse                string
}

type reply struct {
	ExexTime   string
	Second     string
	Cost       string
	Generate   string
	Model      string
	TextModel  string
	ImageModel string
}

type content struct {
	Help   string
	Filter string
	Config string
}

var (
	Lang map[string]Strings
)

func loadLang() {
	Lang = map[string]Strings{}
	Lang["japanese"] = Strings{
		Lang: "japanese",
		Error: errorstr{
			Title:                "エラー",
			Unkown:               "不明なエラーが発生しました。",
			SubCmd:               "引数が不正です。",
			NoModel:              "そのモデルはありません。",
			NoImg:                "画像のURLがありません。",
			TooLongResponse:      "AIの返答が長すぎました。",
			BrokenLink:           "画像のリンクが切れています。",
			NoSupportedFormat:    "この画像フォーマットはサポートしていません。",
			RejectedSafetySystem: "セーフティーシステムにより生成できませんでした。プロンプトを変更し再度お試しください。",
			NoSupportedSize:      "ではこのサイズは対応していません。",
			CantGetImage:         "画像の取得に失敗しました。",
			Invalid:              "コマンドの形式が不正です。",
			NoVisionModel:        "このモデルは画像を読み込めません。",
		},
		Warning: warning{
			Title:                     "注意",
			NoSupportedParameterText:  "このパラメータは`o_series`のみ使用できます。",
			NoSupportedParameterImage: "このパラメータは`dell-e-3`のみ使用できます。",
			DataSaveError:             "データの保存に失敗しました。",
			NoResponse:                "返答がありません。おそらくトークン不足なので、`max_completion_tokens`を増やしてもう一度お試しください。",
		},
		Reply: reply{
			ExexTime:   "実行時間",
			Second:     "秒",
			Cost:       "今月使用した料金：¥ ",
			Generate:   "生成モデル：",
			Model:      "使用可能なモデル一覧",
			TextModel:  "テキストモデル",
			ImageModel: "画像モデル",
		},
		Content: content{
			Help:   "Botの使い方に関しては、Wikiをご覧ください。",
			Filter: "以上の文章をポジティブな言葉で言い換えてください。",
			Config: "設定を変更しました。",
		},
	}
	Lang["english"] = Strings{
		Lang: "english",
		Error: errorstr{
			Title:                "Error",
			Unkown:               "Unknown Error.",
			SubCmd:               "Invalid argument.",
			NoModel:              "The model is nothing.",
			NoImg:                "Nothing Image URL.",
			TooLongResponse:      "Too long response by AI.",
			BrokenLink:           "Thins link has broken.",
			NoSupportedFormat:    "This image format is not supported.",
			RejectedSafetySystem: "Rejected Openai`s safety system.Please change prompt.",
			NoSupportedSize:      "has not supported this size.",
			CantGetImage:         "Fatal to get image.",
			Invalid:              "Invalid command.",
			NoVisionModel:        "This model can't load image.",
		},
		Warning: warning{
			Title:                     "Warning!",
			NoSupportedParameterText:  "This parameter can use `o_series` only.",
			NoSupportedParameterImage: "This parameter can use `dell-e-3` only.",
			DataSaveError:             "Data save error.",
			NoResponse:                "No response. Maybe you need to increase `max_completion_tokens`.",
		},
		Reply: reply{
			ExexTime:   "Execution time: ",
			Second:     "s",
			Cost:       "Fees used in this month: $ ",
			Generate:   "Generated by: ",
			Model:      "Available models: ",
			TextModel:  "Text models",
			ImageModel: "Image models",
		},
		Content: content{
			Help:   "Usage is available on the wiki.",
			Filter: "Please rephrase the above sentence in positives.",
			Config: "Config was changed",
		},
	}
}
