package config

// Type to distinguish model categories
type ModelType string

const (
	ModelTypeText  ModelType = "text"
	ModelTypeImage ModelType = "image"
)

// Structure to consolidate model information
type ModelInfo struct {
	Key          string
	Manufacturer string
	Type         ModelType

	// Text Model
	SupportVision bool
	InputCost     float64 // USD 1M tokens
	OutputCost    float64 // USD 1M tokens

	// Web search Model
	SearchCost SearchCost // USD 1k calls

	// Image Model
	ImageCost map[string]float64
}

type SearchCost struct {
	Low    float64
	Medium float64
	High   float64
}

var AllModels = map[string]ModelInfo{
	"o1-pro": {
		Key:           "o1-pro",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     150.0,
		OutputCost:    600.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o1-pro-2025-03-19": {
		Key:           "o1-pro-2025-03-19",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     150.0,
		OutputCost:    600.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o1": {
		Key:           "o1",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     15.0,
		OutputCost:    60.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o1-2024-12-17": {
		Key:           "o1-2024-12-17",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     15.0,
		OutputCost:    60.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o1-preview": {
		Key:           "o1-preview",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     15.0,
		OutputCost:    60.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o1-preview-2024-09-12": {
		Key:           "o1-preview-2024-09-12",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     15.0,
		OutputCost:    60.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o1-mini": {
		Key:           "o1-mini",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.10,
		OutputCost:    4.40,
		SupportVision: false,
		ImageCost:     nil,
	},
	"o1-mini-2024-09-12": {
		Key:           "o1-mini-2024-09-12",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.10,
		OutputCost:    4.40,
		SupportVision: false,
		ImageCost:     nil,
	},
	"o3": {
		Key:           "o3",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     2.0,
		OutputCost:    8.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o3-2025-04-16": {
		Key:           "o3-2025-04-16",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     2.0,
		OutputCost:    8.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o3-mini": {
		Key:          "o3-mini",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    1.10,
		OutputCost:   4.40,
		ImageCost:    nil,
	},
	"o3-mini-2025-01-31": {
		Key:          "o3-mini-2025-01-31",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    1.10,
		OutputCost:   4.40,
		ImageCost:    nil,
	},
	"o4-mini": {
		Key:           "o4-mini",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.10,
		OutputCost:    4.40,
		SupportVision: true,
		ImageCost:     nil,
	},
	"o4-mini-2025-04-16": {
		Key:           "o4-mini-2025-04-16",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.10,
		OutputCost:    4.40,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5.2-pro": {
		Key:           "gpt-5.2-pro",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     21.0,
		OutputCost:    168.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5.2-pro-2025-12-11": {
		Key:           "gpt-5.2-pro-2025-12-11",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     21.0,
		OutputCost:    168.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-pro": {
		Key:           "gpt-5-pro",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     15.0,
		OutputCost:    120.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-pro-2025-10-06": {
		Key:           "gpt-5-pro-2025-10-06",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     15.0,
		OutputCost:    120.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5.2": {
		Key:           "gpt-5.2",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.75,
		OutputCost:    14.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5.2-2025-12-11": {
		Key:           "gpt-5.2-2025-12-11",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.75,
		OutputCost:    14.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5.2-chat-latest": {
		Key:           "gpt-5.2-chat-latest",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.75,
		OutputCost:    14.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5.1": {
		Key:           "gpt-5.1",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.25,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5.1-2025-11-13": {
		Key:           "gpt-5.1-2025-11-13",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.25,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5.1-chat-latest": {
		Key:           "gpt-5.1-chat-latest",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.25,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5": {
		Key:           "gpt-5",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.25,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-2025-08-07": {
		Key:           "gpt-5-2025-08-07",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.25,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-mini": {
		Key:           "gpt-5-mini",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.25,
		OutputCost:    2.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-mini-2025-08-07": {
		Key:           "gpt-5-mini-2025-08-07",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.25,
		OutputCost:    2.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-nano": {
		Key:           "gpt-5-nano",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.05,
		OutputCost:    0.4,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-nano-2025-08-07": {
		Key:           "gpt-5-nano-2025-08-07",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.05,
		OutputCost:    0.4,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-chat": {
		Key:           "gpt-5-chat",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.25,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-5-chat-latest": {
		Key:           "gpt-5-chat-latest",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     1.25,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},

	"gpt-4.1-2025-04-14": {
		Key:           "gpt-4.1-2025-04-14",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     2.00,
		OutputCost:    8.00,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4.1-mini": {
		Key:           "gpt-4.1-mini",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.40,
		OutputCost:    1.60,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4.1-mini-2025-04-14": {
		Key:           "gpt-4.1-mini-2025-04-14",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.40,
		OutputCost:    1.60,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4.1-nano": {
		Key:           "gpt-4.1-nano",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.10,
		OutputCost:    0.40,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4.1-nano-2025-04-14": {
		Key:           "gpt-4.1-nano-2025-04-14",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.10,
		OutputCost:    0.40,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4.5-preview": {
		Key:           "gpt-4.5-preview",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     75.0,
		OutputCost:    150.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4.5-preview-2025-02-27": {
		Key:           "gpt-4.5-preview-2025-02-27",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     75.0,
		OutputCost:    150.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4o": {
		Key:           "gpt-4o",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     2.50,
		OutputCost:    10.0,
		SupportVision: true,
		SearchCost: SearchCost{
			Low:    30.00,
			Medium: 35.00,
			High:   50.00,
		},
		ImageCost: nil,
	},
	"gpt-4o-search-preview": {
		Key:           "gpt-4o-search-preview",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     2.50,
		OutputCost:    10.0,
		SupportVision: true,
		SearchCost: SearchCost{
			Low:    30.00,
			Medium: 35.00,
			High:   50.00,
		},
		ImageCost: nil,
	},
	"gpt-4o-2024-11-20": {
		Key:           "gpt-4o-2024-11-20",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     2.50,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4o-2024-08-06": {
		Key:           "gpt-4o-2024-08-06",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     2.50,
		OutputCost:    10.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4o-2024-05-13": {
		Key:           "gpt-4o-2024-05-13",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     5.0,
		OutputCost:    15.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4o-mini": {
		Key:           "gpt-4o-mini",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.150,
		OutputCost:    0.600,
		SupportVision: true,
		SearchCost: SearchCost{
			Low:    25.00,
			Medium: 27.50,
			High:   30.00,
		},
		ImageCost: nil,
	},
	"gpt-4o-mini-search-preview": {
		Key:           "gpt-4o-mini-search-preview",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.150,
		OutputCost:    0.600,
		SupportVision: true,
		SearchCost: SearchCost{
			Low:    25.00,
			Medium: 27.50,
			High:   30.00,
		},
		ImageCost: nil,
	},
	"gpt-4o-mini-2024-07-18": {
		Key:           "gpt-4o-mini-2024-07-18",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     0.150,
		OutputCost:    0.600,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4o-latest": {
		Key:           "gpt-4o-latest",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     5.0,
		OutputCost:    15.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4-turbo": {
		Key:           "gpt-4-turbo",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     10.0,
		OutputCost:    30.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4-turbo-2024-04-09": {
		Key:           "gpt-4-turbo-2024-04-09",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     10.0,
		OutputCost:    30.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4-0125-preview": {
		Key:          "gpt-4-0125-preview",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    10.0,
		OutputCost:   30.0,
		ImageCost:    nil,
	},
	"gpt-4-1106-preview": {
		Key:          "gpt-4-1106-preview",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    10.0,
		OutputCost:   30.0,
		ImageCost:    nil,
	},
	"gpt-4-1106-vision-preview": {
		Key:           "gpt-4-1106-vision-preview",
		Manufacturer:  "OpenAI",
		Type:          ModelTypeText,
		InputCost:     10.0,
		OutputCost:    30.0,
		SupportVision: true,
		ImageCost:     nil,
	},
	"gpt-4": {
		Key:          "gpt-4",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    30.0,
		OutputCost:   60.0,
		ImageCost:    nil,
	},
	"gpt-4-0613": {
		Key:          "gpt-4-0613",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    30.0,
		OutputCost:   60.0,
		ImageCost:    nil,
	},
	"gpt-4-0314": {
		Key:          "gpt-4-0314",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    30.0,
		OutputCost:   60.0,
		ImageCost:    nil,
	},
	"gpt-4-32k": {
		Key:          "gpt-4-32k",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    60.0,
		OutputCost:   120.0,
		ImageCost:    nil,
	},
	"gpt-3.5-turbo": {
		Key:          "gpt-3.5-turbo",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    0.50,
		OutputCost:   1.50,
		ImageCost:    nil,
	},
	"gpt-3.5-turbo-0125": {
		Key:          "gpt-3.5-turbo-0125",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    0.50,
		OutputCost:   1.50,
		ImageCost:    nil,
	},
	"gpt-3.5-turbo-1106": {
		Key:          "gpt-3.5-turbo-1106",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    1.0,
		OutputCost:   2.0,
		ImageCost:    nil,
	},
	"gpt-3.5-turbo-0613": {
		Key:          "gpt-3.5-turbo-0613",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    1.50,
		OutputCost:   2.00,
		ImageCost:    nil,
	},
	"gpt-3.5-turbo-instruct": {
		Key:          "gpt-3.5-turbo-instruct",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    1.50,
		OutputCost:   2.00,
		ImageCost:    nil,
	},
	"gpt-3.5-turbo-16k-0613": {
		Key:          "gpt-3.5-turbo-16k-0613",
		Manufacturer: "OpenAI",
		Type:         ModelTypeText,
		InputCost:    3.0,
		OutputCost:   4.0,
		ImageCost:    nil,
	},
	"dall-e-2": {
		Key:          "dall-e-2",
		Manufacturer: "OpenAI",
		Type:         ModelTypeImage,
		ImageCost: map[string]float64{
			"small":  0.0160,
			"medium": 0.0180,
			"big":    0.0200,
		},
	},
	"dall-e-3": {
		Key:          "dall-e-3",
		Manufacturer: "OpenAI",
		Type:         ModelTypeImage,
		ImageCost: map[string]float64{
			"standard-square":    0.040,
			"standard-rectangle": 0.080,
			"hd-square":          0.080,
			"hd-rectangle":       0.120,
		},
	},
	"gpt-image-1": {
		Key:          "gpt-image-1",
		Manufacturer: "OpenAI",
		Type:         ModelTypeImage,
		InputCost:    5.0,
		ImageCost: map[string]float64{
			"low-square":       0.011,
			"low-rectangle":    0.026,
			"medium-square":    0.042,
			"medium-rectangle": 0.063,
			"high-square":      0.167,
			"high-rectangle":   0.250,
		},
	},
	"gpt-image-1-mini": {
		Key:          "gpt-image-1-mini",
		Manufacturer: "OpenAI",
		Type:         ModelTypeImage,
		InputCost:    2.0,
		ImageCost: map[string]float64{
			"low-square":       0.005,
			"low-rectangle":    0.006,
			"medium-square":    0.011,
			"medium-rectangle": 0.015,
			"high-square":      0.036,
			"high-rectangle":   0.052,
		},
	},
	"gpt-image-1.5": {
		Key:          "gpt-image-1.5",
		Manufacturer: "OpenAI",
		Type:         ModelTypeImage,
		InputCost:    5,
		OutputCost:   10,
		ImageCost: map[string]float64{
			"low-square":       0.009,
			"low-rectangle":    0.013,
			"medium-square":    0.034,
			"medium-rectangle": 0.050,
			"high-square":      0.133,
			"high-rectangle":   0.200,
		},
	},
	"gpt-image-1.5-2025-12-16": {
		Key:          "gpt-image-1.5-2025-12-16",
		Manufacturer: "OpenAI",
		Type:         ModelTypeImage,
		InputCost:    5,
		OutputCost:   10,
		ImageCost: map[string]float64{
			"low-square":       0.009,
			"low-rectangle":    0.013,
			"medium-square":    0.034,
			"medium-rectangle": 0.050,
			"high-square":      0.133,
			"high-rectangle":   0.200,
		},
	},
}
